### ISSUE TITLE
how do you do with training and change with this code?

### ISSUE THREAD

**Issue by Bin-ze** [hu64/SpotNet#12]
I found that your code is no different from centernet. There is more knowledge in the semi-supervised-segmentation folder, and the up-sampling segmentation sub-network is not built as in the paper, and there is almost no explanation on how to call in the readme. If you The code completely complies with the calling rules of centernet, then it doesn’t matter, but can you explain where your improvements are, thank you very much for your help。

**Comment by hu64** [comment]
Hi, the segmentation subnetwork is in the large_hourglass, as well as the attention mechanism. The "sampling" file also has some code to load the semi-supervised annotations. This code was released more in the spirit of reproducibility than usability for other users, this might explain why the README is not more developed. Anyhow, hope this helps!

**Comment by Bin-ze** [comment]
thank you your reply,i understand your mean ,your work is very cool ,add attention with centernet is a good idea ,thank you



---Original---
From: "Hughes ***@***.***&gt;
Date: Thu, Jun 17, 2021 02:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hu64/SpotNet] how do you do with training and change with this code? (#12)




 
Hi, the segmentation subnetwork is in the large_hourglass, as well as the attention mechanism. The "sampling" file also has some code to load the semi-supervised annotations. This code was released more in the spirit of reproducibility than usability for other users, this might explain why the README is not more developed. Anyhow, hope this helps!

**Comment by hu64** [comment]
You're welcome, thank you for your interest in our paper!

**Comment by Bin-ze** [comment]
> You're welcome, thank you for your interest in our paper!
I am very interested in your work, and I really want to know if you try to reproduce this kind of work on the COCO data set.
I look forward to communicating with you very much. I would like to do some new research on your work, and I hope to get more detailed information about this work, such as how does it work on other data sets? Can the segmentation attention be more refined to each category?
I look forward to hearing from you

**Comment by hu64** [comment]
Actually, I did try it on COCO, and it didn't improve the performance. I think it's because the attention module has trouble generalizing to a lot of classes, well it's my best hypothesis. I suspect it worked well in my case because the datasets have a limited domain. If you're interested in attention, I recently came across this paper Deformable DETR (https://arxiv.org/abs/2010.04159) where they use location offsets as some kind of self-attention. Anyway, I thought you should check it out. Also, if you refine to more categories, the problem you'll have is that it's going to be a lot harder to produce semi-supervised annotations. And if you have access to fine segmentation annotations, you might want to work on instance segmentation instead.

**Comment by hu64** [comment]
Yeah, I believe your understanding is correct in that the attention is applied on the feature map, not on the center heatmap. To apply it on the heatmaps, I believe you would probably need "class specific attention" (one attention map for each class). If you can train this, then it might work, indeed!
