### ISSUE TITLE
How can i trained this model?

### ISSUE THREAD

**Issue by ghost** [hu64/SpotNet#13]
Please add the steps how to train this model? what is the input and output

**Comment by hu64** [comment]
Hi, thank you for your interest in our paper. The output is the same as CenterNet. For the input, you need the additional foreground/background segmentation to train the attention module. We handle this part in the "sample" file (src/lib/datasets/sample/ctdet.py). Please note that you will have to adapt the path to your system. For further instructions on how to train, I suggest you checkout the original CenterNet GitHub. Our work is strongly based on theirs. To generate the segmentation GT, we used the code in (semi-supervised segmentation/).

**Comment by Bin-ze** [comment]
I noticed that your front background segmentation attention is weighted on the backbone, not on the center point heat map. Then use the weighted features to generate predictions. Is my understanding correct?
Since each class of centernet net will generate a predictive heat map, what I call attention weighting is to weight the objects segmented by the instance on each hot soil. Do you have any thoughts in this regard?
